### ISSUE TITLE
Post toggle off values

### ISSUE THREAD

**Issue by rx** [rx/presenters#60]
In the webclient checkbox/toggle controls don't post when in an off state.

All toggles should always post a name and value. The value should be off if no other value is provided.

**Comment by dsgraham** [comment]
I've bumped into this deficiency in the switch component. I have a solution that is just the addition of an `else` clause in the component's Javascript:
```
    prepareSubmit(params) {
        if (this.input.checked) {
            params.push([this.name(), this.value()]);
        }
        else {
            params.push([this.name(), 'off']);
        }
    }
```
The question is, do we want the switch component to always return input_name = on/off? I think it would be more useful if you could supply an "on" value and "off" value. That would be doable if we change the component to use a two radio inputs instead of a checkbox, which seems like the correct solution to me. 

The default on/off values can be the strings "on" and "off" and it would be backward compatible, assuming no back-end code is using the absence of the parameter as "false/off".
